"""Read DERMO workbooks unchanged and export a separate static source catalog."""
import collections
import hashlib
import json
from pathlib import Path
import openpyxl
from import_supplements import clean, valid_gtin

ROOT = Path(__file__).resolve().parents[1]
FILES = ('cerave.xlsx', 'la-roche-posay.xlsx', 'vichy.xlsx')


def read_records():
    records, sources, issues = [], [], []
    for filename in FILES:
        path = ROOT / 'DERMO' / filename
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
        count = 0
        for sheet in workbook:
            values = iter(sheet.values)
            headers = next(values)
            for row_number, row in enumerate(values, 2):
                if not any(v is not None for v in row):
                    continue
                record = {key: clean(value) for key, value in zip(headers, row) if key}
                if not record.get('product_name_he') or not record.get('brand'):
                    raise ValueError(f'Missing identity at {filename}:{row_number}')
                record['id'] = f'dermo-{path.stem}-{row_number}'
                record['provenance'] = {'file': f'DERMO/{filename}', 'sheet': sheet.title, 'row': row_number, 'sha256': digest}
                record['barcode_original'] = record.get('barcode')
                record['barcode_verification'] = 'source_file_checksum_valid' if valid_gtin(record['barcode']) else 'unconfirmed'
                if not valid_gtin(record['barcode']):
                    record['barcode'] = None
                    issues.append({'id': record['id'], 'issue': 'Invalid or missing source barcode; barcode lookup disabled.'})
                records.append(record)
                count += 1
        workbook.close()
        sources.append({'file': f'DERMO/{filename}', 'sha256': digest, 'products': count})
    valid = [r['barcode'] for r in records if r['barcode']]
    if len(valid) != len(set(valid)):
        raise ValueError('Duplicate dermo barcodes; import halted')
    return records, sources, issues


def main():
    records, sources, issues = read_records()
    catalog = {'schema_version': 1, 'sources': sources, 'products': records,
               'verification_note': 'Source workbook declarations only; no independent clinical verification. Tag filtering is not medical advice.'}
    output = ROOT / 'data'
    output.mkdir(exist_ok=True)
    payload = json.dumps(catalog, ensure_ascii=False, indent=2)
    (output / 'dermo.json').write_text(payload + '\n', encoding='utf-8')
    (output / 'dermo.js').write_text('// Generated by scripts/import_dermo.py; do not edit.\nwindow.DERMO_CATALOG = ' + payload.replace('<', '\\u003c') + ';\n', encoding='utf-8')
    report = {'products': len(records), 'brands': dict(collections.Counter(r['brand'] for r in records)),
              'barcode_statuses': dict(collections.Counter(r['barcode_verification'] for r in records)),
              'source_statuses': dict(collections.Counter(r['verification_status'] for r in records)),
              'sources': sources, 'issues': issues}
    (output / 'dermo-import-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
